# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/common_regression_issues',
                'doc_host': 'https://redam94.github.io',
                'git_url': 'https://github.com/redam94/common_regression_issues',
                'lib_path': 'common_regression_issues'},
  'syms': {'common_regression_issues.core': {'common_regression_issues.core.foo': ('core.html#foo', 'common_regression_issues/core.py')}}}
