"""How to handle panel data"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_group_level_normalization.ipynb.

# %% auto 0
__all__ = ['perform_fixed_effects']

# %% ../nbs/02_group_level_normalization.ipynb 3
import numpy as np
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns
import xarray as xr

# %% ../nbs/02_group_level_normalization.ipynb 8
def perform_fixed_effects(
    df: pd.DataFrame, # Data
    dependent_var: str, # Dependent Variable Name
    independent_var: str, # Independent Variable Name
    group: None|str = None # Grouping Name
    ):
    X = sm.add_constant(df[independent_var])
    y = df[dependent_var]
    if not group is None:
        X = sm.add_constant(df[[independent_var]].join(pd.get_dummies(df[group], drop_first=True).astype(int)))
        model = sm.OLS(y, X).fit(cov_type='cluster', cov_kwds={'groups': pd.factorize(df[group])[0]})
        print(model.summary())
        return model
        
    model = sm.OLS(y, X).fit()
    print(model.summary())
    return model
