"""How to deal with non-stationary, trending or seasonal, time-series and long panel data. WIP"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_trends_and_seasons.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/03_trends_and_seasons.ipynb 2
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pymc as pm
from sklearn.metrics import mean_squared_error, r2_score
import statsmodels.api as sm
import xarray as xr
from tueplots import bundles
from tueplots.constants.color import rgb
from .utils.plotting import rgb_to_hex
